### ISSUE TITLE
UnboundLocalError: local variable 'max_memory' referenced before assignment

### ISSUE THREAD

**Issue by Shiniri** [ji-youn-kim/EHRNoteQA#4]
Seems to me that there are only 2 types of GPU supported in the generation script of this repo and errors / GPUs which are not explicitly mentioned do not get handled, leading to an error where a variable gets mentioned before assignment:

```Python
if "A6000" in torch.cuda.get_device_name():
			max_memory = {i: "48GiB" for i in range(torch.cuda.device_count())}
elif "3090" in torch.cuda.get_device_name():
	max_memory = {i: "24GiB" for i in range(torch.cuda.device_count())}
```

I added my graphics card manually, but in the future a less hard-coded solution may be advisable.

```Python
elif "A100" in torch.cuda.get_device_name():
       max_memory = {i: "80GiB" for i in range(torch.cuda.device_count())}
```

**Comment by ji-youn-kim** [comment]
Hi Shiniri, thanks for pointing this out.
We've updated the code to automatically detect GPU memory, making it more adaptable across different GPU types:
```
max_memory = {}
for i in range(torch.cuda.device_count()):
    total_mem = torch.cuda.get_device_properties(i).total_memory
    total_mem_gib = total_mem / (1024 ** 3)
    max_memory[i] = f"{total_mem_gib:.0f}GiB"
```
You can check it out in the latest master branch :)
